name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build
        required: true
        default: dev
        type: string

jobs:
  build:
    name: Build Chrome and Firefox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Chrome
        run: npm run build:chrome

      - name: Upload Chrome artifact
        uses: actions/upload-artifact@v7
        with:
          name: extension-chrome
          path: dist/
          if-no-files-found: error

      - name: Clean dist
        run: rm -rf dist/

      - name: Build Firefox
        run: npm run build:firefox

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v7
        with:
          name: extension-firefox
          path: dist/
          if-no-files-found: error
